### ISSUE TITLE
Integration with django-allauth

### ISSUE THREAD

**Issue by fatpacket** [thenewguy/django-allauth-adfs#6]
Is there integration with this ADFS provider and django-allauth?  If so is there any documentation or code samples?
Currently running allauth but love the features available with django-allauth-adfs for groups and claim mappings etc.  Any help would be appreciated.

**Comment by thenewguy** [comment]
What troubles are you encountering?

**Comment by fatpacket** [comment]
I have not tried it yet. I am building a new site and loved what allauth brings with user management but found your package. New to a lot of this Django stuff so learning as I go and docs/examples really help. 

Can I just install the package - add the config to settings.py and then auth from my AD tenant? 

Thanks in advance 
-Brant

**Comment by thenewguy** [comment]
Yes. You configure it like an allauth provider. I am happy to help if you have any issues getting it to work. Perhaps you could document what is unclear and add it to the readme

**Comment by fatpacket** [comment]
Thank you. I am having a site design/planning session tomorrow to chart our
project development.
So far we have mocked up a bunch of ideas and the board of my organization
approved my ideas…. Now I need to produce!! So I am starting fresh with a
Django 4+ project with django-invitations, django-allauth and now that I
found your package, I will work on integration.

Thank you for the help.
-Brant

**Comment by thenewguy** [comment]
Sounds good. Going to close this issue. If you hit any trouble open a new specific issue and we'll get you sorted. If you can improve the documentation, a PR would be appreciated
